---
- name: Installs and Configure Metricbeat
  hosts: webservers
  remote_user: sysadmin
  become: yes
  tasks:

    - name: Download Metricbeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
      args:
        warn: false

    - name: Install Metricbeat deb
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    - name: Drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and Configure Docker module
      command: metricbeat modules enable docker

    - name: Setup Metricbeat
      command: metricbeat setup

    - name: Start Metricbeat Service
      service:
        name: metricbeat
        state: started
